#!/usr/bin/env bash

# https://stackoverflow.com/a/246128/6209703
KCPP2_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

KCPP2_INSTALL_PREFIX=$(realpath "$KCPP2_SCRIPT_DIR/..")
KCPP2_PARSER_DIR="$KCPP2_INSTALL_PREFIX/lib/kcpp2/parser/parsing-kompiled"
KCPP2_SEMANTICS_DIR="$KCPP2_INSTALL_PREFIX/lib/kcpp2/semantics/cpp2-kompiled"

set -eu

# Parse arguments
# https://github.com/util-linux/util-linux/blob/master/misc-utils/getopt-example.bash
TEMP=$(getopt --options '' --long 'verbose,result-format:,stop-after-disambiguation,disambiguation-depth:,depth:' -n 'kcpp2' -- "$@")

if [ $? -ne 0 ]; then
	echo 'Terminating...' >&2
	exit 1
fi

eval set -- "$TEMP"
unset TEMP

VERBOSE=
STOP_AFTER_DISAMBIGUATION=
DISAMBIGUATE_DEPTH=
INPUT_FILE=
RESULT_FORMAT="pretty"
DEPTH=

while true; do
	case "$1" in
		'--stop-after-disambiguation')
            STOP_AFTER_DISAMBIGUATION="1"
            shift
			continue
		;;
        '--depth')
            DEPTH="$2"
            shift 2
            continue
        ;;
		'--disambiguation-depth')
            DISAMBIGUATE_DEPTH="$2"
			shift 2
			continue
        ;;
        '--verbose')
            VERBOSE="1"
            shift
            continue
        ;;
        '--result-format')
            RESULT_FORMAT="$2"
            shift 2
            continue
		;;
		'--')
			shift
			break
		;;
        *)
			break
        ;;
	esac
done

execute_command() {
    if [ -n "$VERBOSE" ]; then
        echo "$@";
    fi
    $@
}

parse() {
    echo 'Parsing';
    local input_file="$1";
    local output_file="$2";
    execute_command kparse --definition "$KCPP2_PARSER_DIR" --output-file "$output_file" "$input_file";
}

disambiguate() {
    echo 'Disambiguating';
    local input_file="$1";
    local output_file="$2";
    local krun_args=(--definition "$KCPP2_PARSER_DIR" --output kore --output-file "$output_file" --statistics)
    if [ -n "$DISAMBIGUATE_DEPTH" ]; then
        krun_args+=(--depth "$DISAMBIGUATE_DEPTH");
    fi
    krun_args+=(--parser cat "$input_file")
    execute_command krun ${krun_args[*]};
}

run()          {
    echo 'Running';
    local input_file="$1";
    local krun_args=(--definition "$KCPP2_SEMANTICS_DIR" --output "$RESULT_FORMAT")
    if [ -n "$DEPTH" ]; then
        krun_args+=(--depth "$DEPTH");
    fi
    krun_args+=(--parser cat "$input_file")
    execute_command krun ${krun_args[*]} ;
}


# TODO: work with temporary directories

input_pgm="$1"; shift
parse "$input_pgm" "$input_pgm".deparametrized.kore
disambiguate "$input_pgm".deparametrized.kore "$input_pgm".disambiguated.kore

if [ -n "$STOP_AFTER_DISAMBIGUATION" ]; then
    execute_command kore-print --definition "$KCPP2_PARSER_DIR" --output "$RESULT_FORMAT" "$input_pgm".disambiguated.kore
    exit 0;
fi

prefix="Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'T'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortDeclarations{}, SortKItem{}}("
string=$(cat "$input_pgm".disambiguated.kore)
foo=${string#"$prefix"}
# Remove suffix of the shape suffix="),dotk{}()))),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}(\"$SOMETHING\")))"
# where $SOMETHING is something.
# First, remove the last three closing parentheses and the closing '"'.
suffix1="\")))"
foo=${foo%"$suffix1"}
# Now, remove a number from the end.
foo=$(echo "$foo" | sed -E 's/(.*)([0-9]+)/\1/')
#echo "$foo"
# Now, remove the generated counter.
suffix2=",Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}(\""
foo=${foo%"$suffix2"}
# Now. remove the rest
suffix3="),dotk{}())))"
foo=${foo%"$suffix3"}
#echo "$foo"
echo "inj{SortDeclarations{}, SortTranslationUnit{}}(${foo})" > "$input_pgm".disambiguated.stripped.kore

run "$input_pgm".disambiguated.stripped.kore
